# Generated by Django 4.1.6 on 2023-02-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
