# Generated by Django 4.1.6 on 2023-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message_sent_at_alter_account_user_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='field',
            field=models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('computers', 'Computers'), ('education', 'Education'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('law', 'Law'), ('literature', 'Literature'), ('medicine', 'Medicine'), ('science', 'Science'), ('social_sciences', 'Social Sciences'), ('technology', 'Technology')], default='engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_lang',
            field=models.CharField(choices=[('en', 'English'), ('spa', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('hr', 'Croatian')], default='en', max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='available', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_lang',
            field=models.CharField(choices=[('en', 'English'), ('spa', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('hr', 'Croatian')], default='hr', max_length=3),
        ),
    ]
