# Generated by Django 4.1.6 on 2023-02-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_job_field_alter_job_source_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
