# Generated by Django 4.1.6 on 2023-02-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bid_completed_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='bid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bid'),
            preserve_default=False,
        ),
    ]
